#define LANG
#ifdef  LANG
#define RA "Rigth Ascension"
#define DEC "Declination"
#define ALT "Altitude"
#define AZ "Azimuth"
#define PLANETS "Planets"
#define SUN "Sun"
#define MOON "Moon"
#define MERCURY "Mercury"
#define VENUS "Venus"
#define MARS "Mars"
#define JUPITER "Jupiter"
#define SATURN "Saturn"
#define URANUS "Uranus"
#define NEPTUNE "Neptune"
#define PLUTO "Pluto"
#define WEST "West"
#define EAST "East"
#define NORTH "North"
#define SOUTH "South"
#define HOME "Home"
#define ZENITH "Zenith"
#define SETHOME "Set Home"
#define TRACK "Track"
#define UNTRACK "Untrack"
#define N_POLE "NCP"
#define CONNECT "Connect"
#define CLOSE_CONN "DisConn."
#define PARK "Park"
#define UNPARK "UnPark"
#define GOTO "GoTo"
#define SYNC  "Sync"
#define MODE "Mode"
#define STARS "Stars"
#define STAR1 "Star1"
#define STAR2 "Star2"
#define RESET "Reset"
#define CLEAR "Clr"
#define SEARCH "Search"
#define SEARCHST "SearchSt"
#define GUIDE "GUIDE "
#define CENTER "CENTER "
#define FIND "FIND    "
#define SLEW "SLEW "
#define PARKED "Parked"
#define SLEWING "Slewing"
#define STOPPED "Stop"
#define TRACKING "Tracking"
#define NORMAL_SYNC "NSync"
#define ALING "Aling"
#define ALINGC "AlingC"


#else
#define RA "Ascensión Recta"
#define DEC "Declinación"
#define ALT "Altitud"
#define AZ "Acimut"
#define PLANETS "Planetas"
#define SUN "Sol"
#define MOON "Luna"
#define MERCURY "Mercurio"
#define VENUS "Venus"
#define MARS "Marte"
#define JUPITER "Jupiter"
#define SATURN "Saturno"
#define URANUS "Urano"
#define NEPTUNE "Neptuno"
#define PLUTO "Plutón"
#define WEST "Oeste"
#define EAST "Este"
#define NORTH "Norte"
#define SOUTH "Sur"
#define HOME "Inicio"
#define ZENITH "Cenit"
#define SETHOME "F.Inicio"
#define TRACK "Seguir"
#define UNTRACK "Parar"
#define N_POLE "Polo N"
#define CONNECT "Conectar"
#define CLOSE_CONN "DesCon."
#define PARK "Aparcar"
#define UNPARK "Desaparcar"
#define GOTO "Ir a"
#define SYNC  "Sincr."
#define MODE "Modo"
#define STARS "Estrellas"
#define STAR1 "Estrella1"
#define STAR2 "Estrella2"
#define RESET "Reset"
#define CLEAR "Borrar"
#define SEARCH "Buscar"
#define SEARCHST "Busc.Est"
#define GUIDE "GUIADO  "
#define CENTER "CENTRAR  "
#define FIND "BUSCAR     "
#define SLEW "MÁXIMA  "
#define PARKED "Aparcado"
#define SLEWING "Moviendo"
#define STOPPED "Parado"
#define TRACKING "Siguiendo"
#define NORMAL_SYNC "NSinc."
#define ALING "Alinear"
#define ALINGC "AlinearC"
#endif
#define B_DEL "<-"
